### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by lukebox87** [raney24/brokeSpoke#19]
When trying to sign-out user 'charlotte box-lacey' an error is returned;

TypeError at /signout/54384/0/
can't compare offset-naive and offset-aware datetimes
Request Method:	POST
Request URL:	https://portal.brokespoke.org/signout/54384/0/
Django Version:	3.0.4
Exception Type:	TypeError
Exception Value:	
can't compare offset-naive and offset-aware datetimes
Exception Location:	/app/dashboard/views.py in signout, line 740
Python Executable:	/app/.heroku/python/bin/python
Python Version:	3.6.10
Python Path:	
['/app/.heroku/python/bin',
 '/app',
 '/app/.heroku/python/lib/python36.zip',
 '/app/.heroku/python/lib/python3.6',
 '/app/.heroku/python/lib/python3.6/lib-dynload',
 '/app/.heroku/python/lib/python3.6/site-packages',
 '/app']
Server time:	Tue, 20 Sep 2022 11:10:29 -0400

**Comment by raney24** [comment]
@lukebox87 We couldn't recreate this issue on our end, is still something you all are dealing with?

**Comment by raney24** [comment]
@lukebox87 I believe this was fixed with issue #8, do you know if this is still happening?
